# stable
tab_spaces = 3
newline_style = "Unix"
use_field_init_shorthand = true

# unstable
unstable_features = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
format_code_in_doc_comments = true
reorder_impl_items = true
struct_field_align_threshold = 10
