[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.development]
RUST_LOG = "debug"
RUST_BACKTRACE = 1
RUST_LOG_STYLE = "always"

[tasks.compile-frontend]
description = "Compile Elm source to JavaScript"
script = '''
cd frontend && pnpm elm-spa build
'''

[tasks.build]
description = "Build Tauri application"
dependencies = ["fmt", "compile-frontend"]
command = "cargo"
args = ["tauri", "build"]

[tasks.run]
description = "Run development server"
dependencies = ["fmt", "compile-frontend"]
command = "cargo"
args = ["tauri", "dev"]

[tasks.fmt-backend]
description = "Format Rust code"
cwd = "src-tauri"
script = "cargo +nightly fmt --all"

[tasks.fmt-frontend]
description = "Format Elm code"
cwd = "frontend"
args = ["pnpm", "fmt"]

[tasks.fmt]
description = "Format all source code (Rust and Elm)"
dependencies = ["fmt-backend", "fmt-frontend"]
