[config]
# Skip loading of all core tasks which saves up a bit on toml parsing and task creation
skip_core_tasks = true
# Skips loading Git related environment variables
skip_git_env_info = true
# Skips loading rust related environment variables
skip_rust_env_info = true
# Skips loading the current crate related environment variables
skip_crate_env_info = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[env.development]
RUST_LOG = "debug"
RUST_BACKTRACE = 1
RUST_LOG_STYLE = "always"

[tasks.compile-elm]
description = "Compile Elm source to JavaScript"
script = '''
cd src && elm make src/Main.elm $(find src -name "*.elm" ! -name "Main.elm" -type f) --output=elm.js
'''

[tasks.build]
description = "Build Tauri application"
dependencies = ["fmt", "compile-elm"]
command = "cargo"
args = ["tauri", "build"]

[tasks.run]
description = "Run development server"
dependencies = ["fmt", "compile-elm"]
command = "cargo"
args = ["tauri", "dev"]

[tasks.fmt-rust]
description = "Format Rust code"
cwd = "src-tauri"
script = "cargo +nightly fmt --all"

[tasks.fmt-elm]
description = "Format Elm code"
script = '''
cd src && elm-format src/ --yes
'''

[tasks.fmt]
description = "Format all source code (Rust and Elm)"
dependencies = ["fmt-rust", "fmt-elm"]
